# Generated by Django 5.0.6 on 2024-06-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_image', models.TextField(max_length=200)),
                ('pro_name', models.TextField(max_length=200)),
                ('pro_price', models.TextField(max_length=200)),
            ],
        ),
    ]
