# Generated by Django 5.0.6 on 2024-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairymilk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.TextField(max_length=200)),
                ('con_email', models.CharField(max_length=200)),
                ('con_phone', models.CharField(max_length=200)),
                ('con_message', models.TextField(max_length=200)),
            ],
        ),
    ]
